/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/backends": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The device types CamillaDSP supports. They cannot change while it runs, so
     *     this comes from the cache.
     */
    get: operations["get_backends"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/convcoeffs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * The coefficients of a Conv filter that reads them from a file, and which
     *     samplerate and channel variants of that file exist. The GUI evaluates
     *     filters itself; this exists because only the server can reach the files.
     * @description Not JSON: a little endian u32 giving the length of a JSON `CoeffsHeader`,
     *     that header, padding to the next multiple of 8, and then the samples, in
     *     the width the header gives.
     */
    post: operations["conv_coefficients"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/convolvertojson": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Translate a Convolver config. */
    post: operations["translate_convolver_to_json"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/defaultsforcoeffs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Sensible parameters for a Conv filter reading a coefficient file, from
     *     the file's extension.
     */
    get: operations["get_defaults_for_coeffs"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/devices/{direction}/{backend}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The devices of a device type, or the ones read earlier while CamillaDSP
     *     cannot be reached.
     */
    get: operations["get_devices"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/devices/{direction}/{backend}/capabilities": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The capabilities of a device, or the ones read earlier if CamillaDSP
     *     cannot give them now.
     */
    get: operations["get_device_capabilities"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/eqapotojson": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Translate an Equalizer APO config. */
    post: operations["translate_eqapo_to_json"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/files/{kind}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The files in a folder, sorted by name. */
    get: operations["get_files"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/files/{kind}/delete": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Delete files from a folder. */
    post: operations["delete_files"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/files/{kind}/rename": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Rename a file in a folder. */
    post: operations["rename_file"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/files/{kind}/upload": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Store files in a folder. Uploaded configs have their coefficient and audio
     *     file paths reduced to bare file names, so that configs from other machines
     *     work here.
     */
    post: operations["upload_files"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/files/{kind}/zip": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Some of the files in a folder, as a zip file. */
    post: operations["zip_files"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/getactiveconfigfilename": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The active config file, the one CamillaDSP loads when it starts. */
    get: operations["get_active_config_name"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/getconfig": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The config CamillaDSP runs, with the file paths as CamillaDSP has them. */
    get: operations["get_config"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/getconfigfile": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** A config file, with the file paths relative to the configured folders. */
    get: operations["get_config_file"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/getdefaultconfigfile": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The default config file, `default_config` in the settings, with the file
     *     paths relative to the configured folders.
     */
    get: operations["get_default_config_file"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/getstartconfig": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The config to load into the GUI when it starts: the one in CamillaDSP if
     *     there is one, otherwise the active config file, otherwise the default one.
     */
    get: operations["get_config_at_gui_start"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/guiconfig": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The GUI settings: `gui-config.yml`, and the few settings from
     *     `camillagui.yml` that the frontend needs.
     */
    get: operations["get_gui_config"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/levels": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The VU levels, as a stream of `levels` events.
     * @description The stream has its own subscription, which ends when the browser closes
     *     the stream. Smoothing and rate come from the settings.
     */
    get: operations["get_levels"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/logfile": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** CamillaDSP's log file, `log_file` in the settings. */
    get: operations["get_log_file"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/param/faders": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Every fader, the main volume first, then the aux faders from 1 up. */
    get: operations["get_faders"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/param/faders/{index}/mute": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Mute or unmute a fader. */
    post: operations["set_fader_mute"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/param/faders/{index}/volume": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Set the volume of a fader, in dB. */
    post: operations["set_fader_volume"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/param/mute": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Whether the main volume is muted. */
    get: operations["get_mute"]
    put?: never
    /** Mute or unmute the main volume. */
    post: operations["set_mute"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/param/volume": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The main volume, in dB. */
    get: operations["get_volume"]
    put?: never
    /** Set the main volume, in dB. */
    post: operations["set_volume"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/saveconfigfile": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Save a config to a file in config_dir, with absolute paths so that
     *     CamillaDSP can use it at startup without the GUI.
     */
    post: operations["save_config_file"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/setactiveconfigfile": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Make a config file the active one, the one CamillaDSP loads when it
     *     starts.
     */
    post: operations["set_active_config_name"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/setconfig": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Apply a config. */
    post: operations["set_config"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/spectrum": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The spectrum, as a stream of `spectrum` events.
     * @description The stream has its own subscription, which ends when the browser closes
     *     the stream. The parameters come in the query string, since an EventSource
     *     can only GET.
     */
    get: operations["get_spectrum"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/state": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The processing state, as a stream of `state` events.
     * @description The stream has its own subscription, which ends when the browser closes
     *     the stream. It starts with the current state.
     */
    get: operations["get_state"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The values the GUI polls for, and the versions.
     * @description CamillaDSP is asked at most once a second, however many browsers poll.
     */
    get: operations["get_status"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/stop": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Stop processing. */
    post: operations["stop_processing"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/validateconfig": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Check a config without applying it, with the file paths as the GUI has
     *     them.
     * @description The body is meant to be a config, but any JSON is taken, since a config
     *     that does not parse is reported as an issue like any other.
     */
    post: operations["validate_config"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/wavinfo": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The header of a wav file. */
    get: operations["get_wav_info"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/ymltojson": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Read a YAML file to import from, which may be just part of a config,
     *     migrating it from older versions of CamillaDSP if needed.
     */
    post: operations["yaml_to_json"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ActiveConfigBody: {
      /** @description The file name, in config_dir. */
      name: string
    }
    ActiveConfigFile: {
      /**
       * @description The file name of the active config, null when there is none, or it is
       *     not in config_dir.
       */
      configFileName: string | null
    }
    /** @enum {string} */
    AlsaSampleFormat: "S16_LE" | "S24_3_LE" | "S24_4_LE" | "S32_LE" | "F32_LE" | "F64_LE"
    /** @enum {string} */
    AsioSampleFormat: "S16_LE" | "S24_4_LE" | "S24_3_LE" | "S32_LE" | "F32_LE" | "F64_LE"
    /**
     * @description Polynomial interpolation order for the async polynomial resampler.
     * @enum {string}
     */
    AsyncPolyInterpolation: "Linear" | "Cubic" | "Quintic" | "Septic"
    /**
     * @description Sinc interpolation quality for the async sinc resampler.
     * @enum {string}
     */
    AsyncSincInterpolation: "Nearest" | "Linear" | "Quadratic" | "Cubic"
    /** @description Parameters for the async sinc resampler: either a named profile or free parameters. */
    AsyncSincParameters:
      | {
          profile: components["schemas"]["AsyncSincProfile"]
        }
      | {
          f_cutoff?: components["schemas"]["FiniteF32"] | null
          interpolation: components["schemas"]["AsyncSincInterpolation"]
          oversampling_factor: number
          sinc_len: number
          window: components["schemas"]["AsyncSincWindow"]
        }
    /**
     * @description Preset quality profile for the async sinc resampler.
     * @enum {string}
     */
    AsyncSincProfile: "VeryFast" | "Fast" | "Balanced" | "Accurate"
    /**
     * @description Window function used by the async sinc resampler.
     * @enum {string}
     */
    AsyncSincWindow: "Hann" | "Hann2" | "Blackman" | "Blackman2" | "BlackmanHarris" | "BlackmanHarris2"
    /** @description Full capability descriptor for a named audio device. */
    AudioDeviceDescriptor: {
      /** @description Capability sets, one per access mode supported by the backend. */
      capability_sets: components["schemas"]["DeviceCapabilitySet"][]
      /** @description Human-readable device name. */
      description: string
      /** @description Backend-specific device identifier (e.g. `"hw:0,0"` for ALSA). */
      name: string
    }
    /** @description A device CamillaDSP can use. */
    AvailableDevice: {
      /** @description A readable name. */
      description: string
      /** @description What a config calls it. */
      name: string
    }
    /** @enum {string} */
    BinarySampleFormat: "S16_LE" | "S24_4_RJ_LE" | "S24_4_LJ_LE" | "S24_3_LE" | "S32_LE" | "F32_LE" | "F64_LE"
    /** @description Multi-section biquad combination type (crossover, EQ, tilt, …). */
    BiquadComboParameters:
      | {
          freq: components["schemas"]["FiniteF64"]
          order: number
          /** @enum {string} */
          type: "LinkwitzRileyHighpass"
        }
      | {
          freq: components["schemas"]["FiniteF64"]
          order: number
          /** @enum {string} */
          type: "LinkwitzRileyLowpass"
        }
      | {
          freq: components["schemas"]["FiniteF64"]
          order: number
          /** @enum {string} */
          type: "ButterworthHighpass"
        }
      | {
          freq: components["schemas"]["FiniteF64"]
          order: number
          /** @enum {string} */
          type: "ButterworthLowpass"
        }
      | {
          gain: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "Tilt"
        }
      | {
          bands: components["schemas"]["PeqBand"][]
          /** @enum {string} */
          type: "NPointPeq"
        }
      | (components["schemas"]["GraphicEqualizerParameters"] & {
          /** @enum {string} */
          type: "GraphicEqualizer"
        })
    /** @description Biquad filter type and its frequency/gain/Q parameters. */
    BiquadParameters:
      | {
          a1: components["schemas"]["FiniteF64"]
          a2: components["schemas"]["FiniteF64"]
          b0: components["schemas"]["FiniteF64"]
          b1: components["schemas"]["FiniteF64"]
          b2: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "Free"
        }
      | {
          freq: components["schemas"]["FiniteF64"]
          q: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "Highpass"
        }
      | {
          freq: components["schemas"]["FiniteF64"]
          q: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "Lowpass"
        }
      | (components["schemas"]["PeakingWidth"] & {
          /** @enum {string} */
          type: "Peaking"
        })
      | (components["schemas"]["ShelfSteepness"] & {
          /** @enum {string} */
          type: "Highshelf"
        })
      | {
          freq: components["schemas"]["FiniteF64"]
          gain: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "HighshelfFO"
        }
      | (components["schemas"]["ShelfSteepness"] & {
          /** @enum {string} */
          type: "Lowshelf"
        })
      | {
          freq: components["schemas"]["FiniteF64"]
          gain: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "LowshelfFO"
        }
      | {
          freq: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "HighpassFO"
        }
      | {
          freq: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "LowpassFO"
        }
      | (components["schemas"]["NotchWidth"] & {
          /** @enum {string} */
          type: "Allpass"
        })
      | {
          freq: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "AllpassFO"
        }
      | (components["schemas"]["NotchWidth"] & {
          /** @enum {string} */
          type: "Bandpass"
        })
      | (components["schemas"]["NotchWidth"] & {
          /** @enum {string} */
          type: "Notch"
        })
      | (components["schemas"]["GeneralNotchParams"] & {
          /** @enum {string} */
          type: "GeneralNotch"
        })
      | {
          freq_act: components["schemas"]["FiniteF64"]
          freq_target: components["schemas"]["FiniteF64"]
          q_act: components["schemas"]["FiniteF64"]
          q_target: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "LinkwitzTransform"
        }
    /** @enum {string} */
    CapabilityMode: "Unified" | "Shared" | "Exclusive"
    CaptureDevice:
      | {
          channels: number
          device: string
          format?: components["schemas"]["AlsaSampleFormat"] | null
          labels?: (string | null)[] | null
          link_mute_control?: string | null
          link_volume_control?: string | null
          stop_on_inactive?: boolean | null
          /** @enum {string} */
          type: "Alsa"
        }
      | {
          autoconnect_to?: string | null
          channels: number
          labels?: (string | null)[] | null
          loopback?: boolean | null
          node_description?: string | null
          node_group_name?: string | null
          node_name?: string | null
          /** @enum {string} */
          type: "PipeWire"
        }
      | (components["schemas"]["CaptureDeviceRawFile"] & {
          /** @enum {string} */
          type: "RawFile"
        })
      | (components["schemas"]["CaptureDeviceWavFile"] & {
          /** @enum {string} */
          type: "WavFile"
        })
      | (components["schemas"]["CaptureDeviceStdin"] & {
          /** @enum {string} */
          type: "Stdin"
        })
      | (components["schemas"]["CaptureDeviceCA"] & {
          /** @enum {string} */
          type: "CoreAudio"
        })
      | (components["schemas"]["CaptureDeviceWasapi"] & {
          /** @enum {string} */
          type: "Wasapi"
        })
      | (components["schemas"]["CaptureDeviceAsio"] & {
          /** @enum {string} */
          type: "Asio"
        })
      | {
          channels: number
          labels?: (string | null)[] | null
          signal: components["schemas"]["Signal"]
          /** @enum {string} */
          type: "SignalGenerator"
        }
      | {
          channels: number
          /**
           * Format: int32
           * @description Port of the test control socket, see `src/dummy_backend/control.rs`.
           */
          control_port?: number | null
          labels?: (string | null)[] | null
          signal: components["schemas"]["Signal"]
          /** @enum {string} */
          type: "Dummy"
        }
    CaptureDeviceAsio: {
      channels: number
      device: string
      format?: components["schemas"]["AsioSampleFormat"] | null
      labels?: (string | null)[] | null
    }
    CaptureDeviceCA: {
      channels: number
      device?: string | null
      format?: components["schemas"]["CoreAudioSampleFormat"] | null
      labels?: (string | null)[] | null
    }
    CaptureDeviceRawFile: {
      channels: number
      extra_samples?: number | null
      filename: string
      format: components["schemas"]["BinarySampleFormat"]
      labels?: (string | null)[] | null
      read_bytes?: number | null
      skip_bytes?: number | null
    }
    CaptureDeviceStdin: {
      channels: number
      extra_samples?: number | null
      format: components["schemas"]["BinarySampleFormat"]
      labels?: (string | null)[] | null
      read_bytes?: number | null
      skip_bytes?: number | null
    }
    CaptureDeviceWasapi: {
      channels: number
      device?: string | null
      exclusive?: boolean | null
      format?: components["schemas"]["WasapiSampleFormat"] | null
      labels?: (string | null)[] | null
      loopback?: boolean | null
      polling?: boolean | null
    }
    CaptureDeviceWavFile: {
      extra_samples?: number | null
      filename: string
      labels?: (string | null)[] | null
    }
    /** @description The sample rates (and their formats) supported by a device at a specific channel count. */
    ChannelCapability: {
      /** @description Number of channels. */
      channels: number
      /** @description Supported sample rates for this channel count. */
      samplerates: components["schemas"]["SamplerateCapability"][]
    }
    /** @description Channel display labels returned by [`WsCommand::GetChannelLabels`]. */
    ChannelLabels: {
      /** @description Labels for capture channels. Same structure as `playback`. */
      capture: (string | null)[] | null
      /**
       * @description Labels for playback channels. `null` if no labels are configured. Each entry is a label
       *     string, or `null` if that specific channel has no label.
       */
      playback: (string | null)[] | null
    }
    /** @description Parameters for the hard/soft-clipping filter. */
    ClipperParameters: {
      clip_limit?: components["schemas"]["FiniteF64"]
      soft_clip?: boolean | null
    }
    /**
     * @description Sensible parameters for a Conv filter reading a coefficient file, from the
     *     file's extension. Empty when the extension says nothing.
     */
    CoeffDefaults: {
      format?: components["schemas"]["FileSampleFormat"]
      read_bytes_lines?: number
      skip_bytes_lines?: number
      type?: components["schemas"]["ConvFileType"]
    }
    /** @description The JSON header of a coefficient frame, see `frame_coefficients`. */
    CoeffsHeader: {
      format: components["schemas"]["SampleWidth"]
      /** @description The variants of the file for other samplerates and channel counts. */
      options: components["schemas"]["FilterOption"][]
    }
    CoeffsRequest: {
      /** @description For the `$channels$` token in the file name. */
      channels: number
      /**
       * @description The parameters of a Raw or Wav Conv filter, with the file path as the
       *     GUI has it.
       */
      parameters: components["schemas"]["ConvParameters"]
      /** @description For the `$samplerate$` token in the file name. */
      samplerate: number
    }
    /** @description Parameters for the dynamic range compressor processor. */
    CompressorParameters: {
      attack: components["schemas"]["FiniteF64"]
      attack_unit: components["schemas"]["TimeUnit"]
      channels: number
      clip_limit?: components["schemas"]["FiniteF64"] | null
      factor: components["schemas"]["FiniteF64"]
      makeup_gain?: components["schemas"]["FiniteF64"] | null
      monitor_channels?: number[] | null
      process_channels?: number[] | null
      release: components["schemas"]["FiniteF64"]
      release_unit: components["schemas"]["TimeUnit"]
      soft_clip?: boolean | null
      threshold: components["schemas"]["FiniteF64"]
    }
    ConfigBody: {
      /** @description With the file paths as the GUI has them, relative to the configured folders. */
      config: components["schemas"]["Configuration"]
    }
    /** @description A value in the config that a shortcut controls. */
    ConfigElement: {
      /** @description The keys leading to the value. */
      path: string[]
      /** @description Move this one the opposite way of the control. */
      reverse?: boolean
    }
    /**
     * @description Part of a config, as an import gives it: any of the sections, with any of
     *     the device settings.
     */
    ConfigFragment: {
      description?: string
      devices?: components["schemas"]["DevicesFragment"]
      filters?: {
        [key: string]: components["schemas"]["Filter"]
      }
      mixers?: {
        [key: string]: components["schemas"]["Mixer"]
      }
      pipeline?: components["schemas"]["PipelineStep"][]
      processors?: {
        [key: string]: components["schemas"]["Processor"]
      }
      title?: string
    }
    /**
     * @description Where the config the GUI starts with came from.
     * @enum {string}
     */
    ConfigSource: "dsp" | "active" | "default"
    /** @description A complete CamillaDSP configuration: devices, filters, mixers, processors, and the pipeline. */
    Configuration: {
      description?: string | null
      devices: components["schemas"]["Devices"]
      filters?: {
        [key: string]: components["schemas"]["Filter"]
      } | null
      mixers?: {
        [key: string]: components["schemas"]["Mixer"]
      } | null
      pipeline?: components["schemas"]["PipelineStep"][] | null
      processors?: {
        [key: string]: components["schemas"]["Processor"]
      } | null
      title?: string | null
    }
    /**
     * @description The Conv filter subtypes that read a file.
     * @enum {string}
     */
    ConvFileType: "Raw" | "Wav"
    /** @description Source of convolution coefficients for the FFT convolution filter. */
    ConvParameters:
      | (components["schemas"]["ConvParametersRaw"] & {
          /** @enum {string} */
          type: "Raw"
        })
      | (components["schemas"]["ConvParametersWav"] & {
          /** @enum {string} */
          type: "Wav"
        })
      | {
          /** @enum {string} */
          type: "Values"
          values: components["schemas"]["FiniteF64"][]
        }
      | {
          length: number
          /** @enum {string} */
          type: "Dummy"
        }
    /** @description Coefficients loaded from a raw binary or text file. */
    ConvParametersRaw: {
      filename: string
      format?: components["schemas"]["FileSampleFormat"] | null
      read_bytes_lines?: number | null
      skip_bytes_lines?: number | null
    }
    /** @description Coefficients loaded from a specific channel of a WAV file. */
    ConvParametersWav: {
      channel?: number | null
      filename: string
    }
    /** @enum {string} */
    CoreAudioSampleFormat: "S16" | "S24" | "S32" | "F32"
    /** @description Parameters for a time-delay filter. */
    DelayParameters: {
      delay: components["schemas"]["FiniteF64"]
      delay_unit: components["schemas"]["DelayUnit"]
      subsample?: boolean | null
    }
    /**
     * @description Unit for a time or distance value used by delays (Delay filter, RACE processor).
     * @enum {string}
     */
    DelayUnit: "us" | "ms" | "s" | "mm" | "samples"
    /** @description A set of device capabilities associated with a single access mode (e.g. exclusive vs. shared). */
    DeviceCapabilitySet: {
      /** @description Per-channel-count capability entries. */
      capabilities: components["schemas"]["ChannelCapability"][]
      /** @description The access mode these capabilities were probed under. */
      mode: components["schemas"]["CapabilityMode"]
    }
    /** @description The device types a CamillaDSP build supports. */
    DeviceTypeLists: {
      capture: string[]
      playback: string[]
    }
    /** @description Top-level device and pipeline timing configuration. */
    Devices: {
      adjust_interval_s?: components["schemas"]["FiniteF32"] | null
      capture: components["schemas"]["CaptureDevice"]
      capture_samplerate?: number | null
      /** @description Number of frames per processing chunk. */
      chunksize: number
      enable_rate_adjust?: boolean | null
      multithreaded?: boolean | null
      playback: components["schemas"]["PlaybackDevice"]
      queuelimit?: number | null
      rate_measure_interval_s?: components["schemas"]["FiniteF32"] | null
      resampler?: components["schemas"]["Resampler"] | null
      /** @description Output sample rate in Hz. */
      samplerate: number
      silence_threshold?: components["schemas"]["FiniteF64"] | null
      silence_timeout_s?: components["schemas"]["FiniteF64"] | null
      stop_on_rate_change?: boolean | null
      target_level?: number | null
      volume_limit?: components["schemas"]["FiniteF32"] | null
      volume_ramp_time_ms?: components["schemas"]["FiniteF32"] | null
      worker_threads?: number | null
    }
    /**
     * @description Any of the device settings, since an import may have only some of them.
     *     The fields of camilladsp-config's `Devices`, every one optional and left
     *     out when the import does not have it.
     */
    DevicesFragment: {
      adjust_interval_s?: components["schemas"]["FiniteF32"]
      capture?: components["schemas"]["CaptureDevice"]
      capture_samplerate?: number
      chunksize?: number
      enable_rate_adjust?: boolean
      multithreaded?: boolean
      playback?: components["schemas"]["PlaybackDevice"]
      queuelimit?: number
      rate_measure_interval_s?: components["schemas"]["FiniteF32"]
      resampler?: components["schemas"]["Resampler"]
      samplerate?: number
      silence_threshold?: components["schemas"]["FiniteF64"]
      silence_timeout_s?: components["schemas"]["FiniteF64"]
      stop_on_rate_change?: boolean
      target_level?: number
      volume_limit?: components["schemas"]["FiniteF32"]
      volume_ramp_time_ms?: components["schemas"]["FiniteF32"]
      worker_threads?: number
    }
    /** @description Parameters for the difference-equation (IIR) filter: `a` (feedback) and `b` (feedforward) coefficients. */
    DiffEqParameters: {
      a?: components["schemas"]["FiniteF64"][] | null
      b?: components["schemas"]["FiniteF64"][] | null
    }
    /**
     * @description Which side of CamillaDSP a device is on.
     * @enum {string}
     */
    Direction: "capture" | "playback"
    /** @description Dithering algorithm and bit depth for the dither filter. */
    DitherParameters:
      | {
          bits: number
          /** @enum {string} */
          type: "None"
        }
      | {
          amplitude: components["schemas"]["FiniteF64"]
          bits: number
          /** @enum {string} */
          type: "Flat"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "Highpass"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "Fweighted441"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "FweightedLong441"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "FweightedShort441"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "Gesemann441"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "Gesemann48"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "Lipshitz441"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "LipshitzLong441"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "Shibata441"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "ShibataHigh441"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "ShibataLow441"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "Shibata48"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "ShibataHigh48"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "ShibataLow48"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "Shibata882"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "ShibataLow882"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "Shibata96"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "ShibataLow96"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "Shibata192"
        }
      | {
          bits: number
          /** @enum {string} */
          type: "ShibataLow192"
        }
    EqApoImport: {
      /**
       * Format: int64
       * @description The number of channels, which decides what the channel names map to.
       */
      channels: number
      /** @description The text of the Equalizer APO config. */
      text: string
    }
    /** @description The body of every error response. */
    ErrorBody: {
      /** @description What went wrong, to show to the user. */
      message: string
      /**
       * @description When CamillaDSP refused a command, the name of its error, for example
       *     `ProcessingNotRunningError`.
       */
      result?: string | null
    }
    /** @description Volume and mute state for one fader, as returned by [`WsCommand::GetFaders`]. */
    Fader: {
      /** @description Whether the fader is muted. */
      mute: boolean
      /**
       * Format: float
       * @description Current volume in dB.
       */
      volume: number
    }
    /**
     * @description A file in a listing. What is known about it beyond its name, size and time
     *     depends on the folder: configs have their title, version and validity, and
     *     wav files their format. What is not known is left out.
     */
    FileInfo: {
      /** @description For a wav file. */
      channels?: number
      /** @description For a config, its description. */
      description?: string
      /**
       * Format: double
       * @description For a wav file, in seconds.
       */
      duration?: number
      /** @description For a config, its errors and warnings. */
      errors?: components["schemas"]["ValidationIssue"][]
      /**
       * Format: double
       * @description The time of the last change, in seconds since the epoch.
       */
      lastModified: number
      name: string
      /** @description For a wav file, the CamillaDSP name of its sample format. */
      sampleformat?: string
      /** @description For a wav file, in Hz. */
      samplerate?: number
      /**
       * Format: int64
       * @description In bytes.
       */
      size: number
      /** @description For a config, its title. */
      title?: string
      /**
       * @description For a config, whether it has no errors. For a wav file, whether
       *     CamillaDSP can read it.
       */
      valid?: boolean
      /**
       * Format: int32
       * @description For a config, the CamillaDSP version it is for.
       */
      version?: number
    }
    /**
     * @description One of the folders the GUI keeps files in.
     * @enum {string}
     */
    FileKind: "config" | "coeff" | "audiofile"
    FileNames: {
      /** @description File names, in the folder. */
      names: string[]
    }
    /**
     * @description Sample format used for coefficient files; extends [`BinarySampleFormat`] with a plain-text variant.
     * @enum {string}
     */
    FileSampleFormat: "TEXT" | "S16_LE" | "S24_4_RJ_LE" | "S24_4_LJ_LE" | "S24_3_LE" | "S32_LE" | "F32_LE" | "F64_LE"
    /** @description Filter type selector; each variant carries its own parameter struct. */
    Filter:
      | {
          description?: string | null
          parameters: components["schemas"]["ConvParameters"]
          /** @enum {string} */
          type: "Conv"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["BiquadParameters"]
          /** @enum {string} */
          type: "Biquad"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["BiquadComboParameters"]
          /** @enum {string} */
          type: "BiquadCombo"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["DelayParameters"]
          /** @enum {string} */
          type: "Delay"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["GainParameters"]
          /** @enum {string} */
          type: "Gain"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["VolumeParameters"]
          /** @enum {string} */
          type: "Volume"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["LoudnessParameters"]
          /** @enum {string} */
          type: "Loudness"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["DitherParameters"]
          /** @enum {string} */
          type: "Dither"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["DiffEqParameters"]
          /** @enum {string} */
          type: "DiffEq"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["ClipperParameters"]
          /** @enum {string} */
          type: "Clipper"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["LookaheadLimiterParameters"]
          /** @enum {string} */
          type: "LookaheadLimiter"
        }
    /**
     * @description A variant of a coefficient file that exists, with the samplerate and
     *     channels its name gives for the `$samplerate$` and `$channels$` tokens.
     */
    FilterOption: {
      /** Format: int64 */
      channels?: number
      name: string
      /** Format: int64 */
      samplerate?: number
    }
    /** Format: float */
    FiniteF32: number
    /** Format: double */
    FiniteF64: number
    /** @description Parameters for the static gain filter. */
    GainParameters: {
      gain: components["schemas"]["FiniteF64"]
      inverted?: boolean | null
      mute?: boolean | null
      scale?: components["schemas"]["GainScale"] | null
    }
    /**
     * @description Whether a gain value is interpreted as a linear factor or in decibels.
     * @enum {string}
     */
    GainScale: "linear" | "dB"
    /** @description Parameters for the general (asymmetric pole/zero) notch biquad. */
    GeneralNotchParams: {
      freq_p: components["schemas"]["FiniteF64"]
      freq_z: components["schemas"]["FiniteF64"]
      normalize_at_dc?: boolean | null
      q_p: components["schemas"]["FiniteF64"]
    }
    /** @description Parameters for the graphic equalizer biquad combo filter. */
    GraphicEqualizerParameters: {
      freq_max?: components["schemas"]["FiniteF32"] | null
      freq_min?: components["schemas"]["FiniteF32"] | null
      gains: components["schemas"]["FiniteF32"][]
    }
    /**
     * @description The GUI settings: `gui-config.yml`, and the few settings from
     *     `camillagui.yml` that the frontend needs.
     */
    GuiConfig: {
      allow_absolute_paths: boolean
      apply_config_automatically: boolean
      /** @description Whether an audiofiles_dir is set. */
      audiofiles_supported: boolean
      /** @description Whether the backend can store which config file is the active one. */
      can_update_active_config: boolean
      /**
       * @description coeff_dir, relative to config_dir and ending with a separator, from
       *     `camillagui.yml` like the rest below.
       */
      coeff_dir: string
      custom_shortcuts: components["schemas"]["ShortcutSection"][]
      hide_capture_device: boolean
      hide_capture_samplerate: boolean
      hide_multithreading: boolean
      hide_playback_device: boolean
      hide_rate_monitoring: boolean
      hide_silence: boolean
      /** @description The title of the browser tab. */
      page_title: string
      save_config_automatically: boolean
      /** Format: double */
      spectrum_max_db: number
      /**
       * Format: double
       * @description In Hz.
       */
      spectrum_max_freq: number
      /**
       * Format: float
       * @description The most spectrum updates per second.
       */
      spectrum_max_rate: number
      /** Format: double */
      spectrum_min_db: number
      /**
       * Format: double
       * @description In Hz.
       */
      spectrum_min_freq: number
      spectrum_n_bins: number
      /**
       * Format: int32
       * @description In milliseconds.
       */
      status_update_interval: number
      supported_capture_types: string[] | null
      supported_playback_types: string[] | null
      /**
       * Format: int32
       * @description The top of the volume sliders, in dB.
       */
      volume_max: number
      /**
       * Format: double
       * @description The range of the volume sliders, in dB.
       */
      volume_range: number
    }
    ImportText: {
      /** @description The text of the file to import from. */
      text: string
    }
    LookaheadLimiterParameters: {
      attack: components["schemas"]["FiniteF64"]
      attack_unit: components["schemas"]["TimeUnit"]
      limit?: components["schemas"]["FiniteF64"]
      release: components["schemas"]["FiniteF64"]
      release_unit: components["schemas"]["TimeUnit"]
    }
    /** @description Parameters for the multichannel lookahead limiter processor. */
    LookaheadLimiterProcessorParameters: {
      attack: components["schemas"]["FiniteF64"]
      attack_unit: components["schemas"]["TimeUnit"]
      channels: number
      delay_processed_only?: boolean | null
      limit?: components["schemas"]["FiniteF64"]
      monitor_channels?: number[] | null
      process_channels?: number[] | null
      release: components["schemas"]["FiniteF64"]
      release_unit: components["schemas"]["TimeUnit"]
    }
    /**
     * @description Which fader drives the loudness filter's compensation level.
     * @enum {string}
     */
    LoudnessFader: "Main" | "Aux1" | "Aux2" | "Aux3" | "Aux4"
    /** @description Parameters for the loudness (Fletcher-Munson) compensation filter. */
    LoudnessParameters: {
      attenuate_mid?: boolean | null
      fader?: components["schemas"]["LoudnessFader"] | null
      high_boost?: components["schemas"]["FiniteF32"] | null
      high_freq?: components["schemas"]["FiniteF64"] | null
      high_q?: components["schemas"]["FiniteF64"] | null
      low_boost?: components["schemas"]["FiniteF32"] | null
      low_freq?: components["schemas"]["FiniteF64"] | null
      low_q?: components["schemas"]["FiniteF64"] | null
      reference_level: components["schemas"]["FiniteF32"]
    }
    /** @description Configuration for a named mixer: channel counts, routing rules, and optional labels. */
    Mixer: {
      channels: components["schemas"]["MixerChannels"]
      description?: string | null
      labels?: (string | null)[] | null
      mapping: components["schemas"]["MixerMapping"][]
    }
    /** @description Input and output channel counts for a mixer. */
    MixerChannels: {
      in: number
      out: number
    }
    /** @description Routing rule: which sources feed a given destination channel in a mixer. */
    MixerMapping: {
      dest: number
      mute?: boolean | null
      sources: components["schemas"]["MixerSource"][]
    }
    /** @description One input source contributing to a mixer output channel. */
    MixerSource: {
      channel: number
      gain?: components["schemas"]["FiniteF64"] | null
      inverted?: boolean | null
      mute?: boolean | null
      scale?: components["schemas"]["GainScale"] | null
    }
    /** @description Parameters for the noise gate processor. */
    NoiseGateParameters: {
      attack: components["schemas"]["FiniteF64"]
      attack_unit: components["schemas"]["TimeUnit"]
      attenuation: components["schemas"]["FiniteF64"]
      channels: number
      monitor_channels?: number[] | null
      process_channels?: number[] | null
      release: components["schemas"]["FiniteF64"]
      release_unit: components["schemas"]["TimeUnit"]
      threshold: components["schemas"]["FiniteF64"]
    }
    /** @description Notch / allpass / bandpass width specified either as a Q factor or a bandwidth in octaves. */
    NotchWidth:
      | {
          freq: components["schemas"]["FiniteF64"]
          q: components["schemas"]["FiniteF64"]
        }
      | {
          bandwidth: components["schemas"]["FiniteF64"]
          freq: components["schemas"]["FiniteF64"]
        }
    /**
     * @description One step on the way to the value an issue is about: a map key or a list index.
     *
     *     Serialized untagged, so a path comes out as a plain list such as
     *     `["pipeline", 2, "names", 0]`.
     */
    PathElement: string | number
    /** @description Peaking filter width specified either as a Q factor or a bandwidth in octaves. */
    PeakingWidth:
      | {
          freq: components["schemas"]["FiniteF64"]
          gain: components["schemas"]["FiniteF64"]
          q: components["schemas"]["FiniteF64"]
        }
      | {
          bandwidth: components["schemas"]["FiniteF64"]
          freq: components["schemas"]["FiniteF64"]
          gain: components["schemas"]["FiniteF64"]
        }
    /**
     * @description One band of an NPointPeq parametric equalizer.
     *
     *     The role of a band follows its position in the list: the first one is a low shelf,
     *     the last one a high shelf, and the ones in between are peaking filters.
     */
    PeqBand: {
      freq: components["schemas"]["FiniteF64"]
      gain: components["schemas"]["FiniteF64"]
      q: components["schemas"]["FiniteF64"]
    }
    /** @description One step in the processing pipeline: a mixer, filter chain, or processor. */
    PipelineStep:
      | (components["schemas"]["PipelineStepMixer"] & {
          /** @enum {string} */
          type: "Mixer"
        })
      | (components["schemas"]["PipelineStepFilter"] & {
          /** @enum {string} */
          type: "Filter"
        })
      | (components["schemas"]["PipelineStepProcessor"] & {
          /** @enum {string} */
          type: "Processor"
        })
    /** @description Configuration for a filter pipeline step. */
    PipelineStepFilter: {
      bypassed?: boolean | null
      channels?: number[] | null
      description?: string | null
      names: string[]
    }
    /** @description Configuration for a mixer pipeline step. */
    PipelineStepMixer: {
      bypassed?: boolean | null
      description?: string | null
      name: string
    }
    /** @description Configuration for a processor pipeline step. */
    PipelineStepProcessor: {
      bypassed?: boolean | null
      description?: string | null
      name: string
    }
    PlaybackDevice:
      | {
          channels: number
          device: string
          format?: components["schemas"]["AlsaSampleFormat"] | null
          /** @enum {string} */
          type: "Alsa"
        }
      | {
          autoconnect_to?: string | null
          channels: number
          node_description?: string | null
          node_group_name?: string | null
          node_name?: string | null
          /** @enum {string} */
          type: "PipeWire"
        }
      | {
          channels: number
          filename: string
          format: components["schemas"]["BinarySampleFormat"]
          /** @enum {string} */
          type: "File"
          /**
           * @description Write an RF64 header so the file can grow past the 4 GB limit of plain
           *     wav. Only applies when `wav_header` is true; ignored otherwise.
           */
          use_rf64?: boolean | null
          wav_header?: boolean | null
        }
      | {
          channels: number
          format: components["schemas"]["BinarySampleFormat"]
          /** @enum {string} */
          type: "Stdout"
          wav_header?: boolean | null
        }
      | (components["schemas"]["PlaybackDeviceCA"] & {
          /** @enum {string} */
          type: "CoreAudio"
        })
      | (components["schemas"]["PlaybackDeviceWasapi"] & {
          /** @enum {string} */
          type: "Wasapi"
        })
      | (components["schemas"]["PlaybackDeviceAsio"] & {
          /** @enum {string} */
          type: "Asio"
        })
      | {
          channels: number
          /**
           * Format: int32
           * @description Port of the test control socket, see `src/dummy_backend/control.rs`.
           */
          control_port?: number | null
          format?: components["schemas"]["BinarySampleFormat"] | null
          /** @enum {string} */
          type: "Dummy"
        }
    PlaybackDeviceAsio: {
      channels: number
      device: string
      format?: components["schemas"]["AsioSampleFormat"] | null
    }
    PlaybackDeviceCA: {
      channels: number
      device?: string | null
      exclusive?: boolean | null
      format?: components["schemas"]["CoreAudioSampleFormat"] | null
    }
    PlaybackDeviceWasapi: {
      channels: number
      device?: string | null
      exclusive?: boolean | null
      format?: components["schemas"]["WasapiSampleFormat"] | null
      polling?: boolean | null
    }
    /**
     * @description The state of the processing, as reported by [`WsCommand::GetState`].
     * @enum {string}
     */
    ProcessingState: "Running" | "Paused" | "Inactive" | "Starting" | "Stalled"
    /** @description Processor type selector; each variant carries its own parameter struct. */
    Processor:
      | {
          description?: string | null
          parameters: components["schemas"]["CompressorParameters"]
          /** @enum {string} */
          type: "Compressor"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["NoiseGateParameters"]
          /** @enum {string} */
          type: "NoiseGate"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["LookaheadLimiterProcessorParameters"]
          /** @enum {string} */
          type: "LookaheadLimiter"
        }
      | {
          description?: string | null
          parameters: components["schemas"]["RACEParameters"]
          /** @enum {string} */
          type: "RACE"
        }
    /** @description Parameters for the RACE (Recursive Ambiophonic Crosstalk Elimination) processor. */
    RACEParameters: {
      attenuation: components["schemas"]["FiniteF64"]
      channel_a: number
      channel_b: number
      channels: number
      delay: components["schemas"]["FiniteF64"]
      delay_unit: components["schemas"]["DelayUnit"]
      subsample_delay?: boolean | null
    }
    RenameBody: {
      /** @description The file name, in the folder. */
      source: string
      /** @description The new file name, in the same folder. */
      target: string
    }
    /** @description Resampler algorithm selection. */
    Resampler:
      | {
          interpolation: components["schemas"]["AsyncPolyInterpolation"]
          /** @enum {string} */
          type: "AsyncPoly"
        }
      | (components["schemas"]["AsyncSincParameters"] & {
          /** @enum {string} */
          type: "AsyncSinc"
        })
      | {
          /** @enum {string} */
          type: "Synchronous"
        }
      | {
          /** @enum {string} */
          type: "Slip"
        }
    /**
     * @description The width of the samples in a coefficient frame.
     * @enum {string}
     */
    SampleWidth: "float32" | "float64"
    /** @description The sample formats supported by a device at a specific sample rate. */
    SamplerateCapability: {
      /** @description Names of the supported sample formats at this rate. */
      formats: string[]
      /** @description Sample rate in Hz. */
      samplerate: number
    }
    SaveConfigBody: {
      /** @description With the file paths as the GUI has them, relative to the configured folders. */
      config: components["schemas"]["Configuration"]
      /** @description The file name, in config_dir. */
      filename: string
    }
    /**
     * @description How much an issue matters to the GUI.
     * @enum {string}
     */
    Severity: "error" | "warning"
    /** @description Shelf steepness specified either as a Q factor or a slope in dB/octave. */
    ShelfSteepness:
      | {
          freq: components["schemas"]["FiniteF64"]
          gain: components["schemas"]["FiniteF64"]
          q: components["schemas"]["FiniteF64"]
        }
      | {
          freq: components["schemas"]["FiniteF64"]
          gain: components["schemas"]["FiniteF64"]
          slope: components["schemas"]["FiniteF64"]
        }
    /** @description A control for one or more values in the config. */
    Shortcut: {
      /**
       * @description The values it controls. The control shows the first one, the others
       *     follow it.
       */
      config_elements: components["schemas"]["ConfigElement"][]
      description?: string
      name: string
      /**
       * Format: double
       * @description Needed for a number.
       */
      range_from?: number
      /**
       * Format: double
       * @description Needed for a number.
       */
      range_to?: number
      /**
       * Format: double
       * @description Needed for a number.
       */
      step?: number
      /** @description A slider when not given. */
      type?: components["schemas"]["ShortcutType"]
    }
    /** @description A group of shortcuts, with a heading. */
    ShortcutSection: {
      description?: string
      section: string
      shortcuts: components["schemas"]["Shortcut"][]
    }
    /** @enum {string} */
    ShortcutType: "boolean" | "number"
    /** @description Signal type generated by the `SignalGenerator` capture device. */
    Signal:
      | {
          freq: components["schemas"]["FiniteF64"]
          level: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "Sine"
        }
      | {
          freq: components["schemas"]["FiniteF64"]
          level: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "Square"
        }
      | {
          level: components["schemas"]["FiniteF64"]
          /** @enum {string} */
          type: "WhiteNoise"
        }
    /** @description Log-spaced spectrum, as returned by [`WsCommand::GetSpectrum`]. */
    SpectrumData: {
      /** @description Center frequency of each output bin in Hz. */
      frequencies: number[]
      /** @description Per-bin peak magnitude in dBFS (0 dBFS = full-scale sine wave). */
      magnitudes: number[]
    }
    StartConfig: {
      config: components["schemas"]["Configuration"]
      /** @description The file the config came from, null if it is not known. */
      configFileName: string | null
      source: components["schemas"]["ConfigSource"]
    }
    /** @description Payload of a [`WsReply::StateEvent`] pushed by [`WsCommand::SubscribeState`]. */
    StateUpdate: {
      state: components["schemas"]["ProcessingState"]
      stop_reason?: components["schemas"]["StopReason"] | null
    }
    /**
     * @description What `GET /api/status` answers. The processing state is not here, it comes
     *     from `/api/state` as it changes. A value CamillaDSP declines to give, for
     *     example with no config loaded, is null, and so is every value while it is
     *     offline.
     */
    Status: {
      /** @description The version of this backend. */
      backend_version: string
      bufferlevel: number | null
      /**
       * @description The capture rate in Hz, rounded to the nearest standard rate. Null when
       *     it is not within 4% of one.
       */
      capturerate: number | null
      /** @description Whether CamillaDSP answered the last time it was asked. */
      cdsp_online: boolean
      /** @description CamillaDSP's version, `(offline)` until it has been reached. */
      cdsp_version: string
      clippedsamples: number | null
      description: string | null
      labels: components["schemas"]["ChannelLabels"]
      /**
       * Format: float
       * @description In percent.
       */
      processingload: number | null
      /** Format: float */
      rateadjust: number | null
      /**
       * Format: float
       * @description In percent.
       */
      resamplerload: number | null
      title: string | null
    }
    /** @description Reason a processing run ended. */
    StopReason:
      | "None"
      | "Done"
      | {
          /** @description Capture device reported an error. */
          CaptureError: string
        }
      | {
          /** @description Playback device reported an error. */
          PlaybackError: string
        }
      | {
          /** @description An unexpected internal error occurred. */
          UnknownError: string
        }
      | {
          /** @description Capture device sample rate changed to the given value. */
          CaptureFormatChange: number
        }
      | {
          /** @description Playback device sample rate changed to the given value. */
          PlaybackFormatChange: number
        }
    /**
     * @description Unit for a time value (attack, release, envelope times).
     * @enum {string}
     */
    TimeUnit: "us" | "ms" | "s" | "samples"
    /** @description Files to upload, as `multipart/form-data`. */
    UploadForm: {
      /**
       * @description The files, each with its file name. A file of the same name is
       *     replaced.
       */
      files: string[]
    }
    /** @description A problem with a config. */
    ValidationIssue: {
      message: string
      /**
       * @description Where in the config, as keys and list indices from the top. Empty for
       *     the config as a whole.
       */
      path: components["schemas"]["PathElement"][]
      severity: components["schemas"]["Severity"]
    }
    /**
     * @description Which aux fader a Volume filter is linked to (faders 1–4; the main fader is always 0).
     * @enum {string}
     */
    VolumeFader: "Aux1" | "Aux2" | "Aux3" | "Aux4"
    /** @description Parameters for the volume-ramp filter linked to a specific fader. */
    VolumeParameters: {
      fader: components["schemas"]["VolumeFader"]
      limit?: components["schemas"]["FiniteF32"] | null
      ramp_time_ms?: components["schemas"]["FiniteF32"] | null
    }
    /**
     * @description Payload of a [`WsReply::VuLevelsEvent`] pushed by [`WsCommand::SubscribeVuLevels`].
     *
     *     All values are smoothed dB levels, per channel.
     */
    VuLevels: {
      capture_peak: number[]
      capture_rms: number[]
      playback_peak: number[]
      playback_rms: number[]
    }
    /** @enum {string} */
    WasapiSampleFormat: "S16" | "S24" | "S32" | "F32"
    /** @description The header of a wav file. */
    WavInfo: {
      /** Format: int32 */
      bitspersample: number
      /** Format: int32 */
      byterate: number
      /** Format: int32 */
      bytesperframe: number
      channels: number
      /** Format: int64 */
      datalength: number
      /** Format: int64 */
      dataoffset: number
      sampleformat: string
      samplerate: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_backends: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Null until CamillaDSP has been reached */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["DeviceTypeLists"] | null
        }
      }
    }
  }
  conv_coefficients: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CoeffsRequest"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/octet-stream": string
        }
      }
      /** @description The filter reads no file, or the file could not be read */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description The file is outside the configured folders */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description There is no such file */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  translate_convolver_to_json: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportText"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ConfigFragment"]
        }
      }
      /** @description The text is not a Convolver config */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_defaults_for_coeffs: {
    parameters: {
      query: {
        /** @description The coefficient file, relative to config_dir. */
        file: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CoeffDefaults"]
        }
      }
    }
  }
  get_devices: {
    parameters: {
      query?: never
      header?: never
      path: {
        direction: components["schemas"]["Direction"]
        /** @description The device type, for example `Alsa` */
        backend: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AvailableDevice"][]
        }
      }
      /** @description CamillaDSP refused */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_device_capabilities: {
    parameters: {
      query: {
        /** @description The device, as a config names it. */
        device: string
      }
      header?: never
      path: {
        direction: components["schemas"]["Direction"]
        /** @description The device type, for example `Alsa` */
        backend: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AudioDeviceDescriptor"]
        }
      }
      /** @description No device is given, or CamillaDSP refused */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description CamillaDSP cannot be reached */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  translate_eqapo_to_json: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["EqApoImport"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ConfigFragment"]
        }
      }
      /** @description The body is not valid */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_files: {
    parameters: {
      query?: never
      header?: never
      path: {
        kind: components["schemas"]["FileKind"]
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FileInfo"][]
        }
      }
      /** @description No audiofiles_dir is set */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  delete_files: {
    parameters: {
      query?: never
      header?: never
      path: {
        kind: components["schemas"]["FileKind"]
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["FileNames"]
      }
    }
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No audiofiles_dir is set */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description A file could not be deleted */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  rename_file: {
    parameters: {
      query?: never
      header?: never
      path: {
        kind: components["schemas"]["FileKind"]
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameBody"]
      }
    }
    responses: {
      /** @description Renamed */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description A file name is not valid, the new name is taken, or the file could not be renamed */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description No audiofiles_dir is set */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  upload_files: {
    parameters: {
      query?: never
      header?: never
      path: {
        kind: components["schemas"]["FileKind"]
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["UploadForm"]
      }
    }
    responses: {
      /** @description Stored */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description A file name is not valid */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description No audiofiles_dir is set */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description The folder does not exist, or a file could not be written */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  zip_files: {
    parameters: {
      query?: never
      header?: never
      path: {
        kind: components["schemas"]["FileKind"]
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["FileNames"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/octet-stream": string
        }
      }
      /** @description No audiofiles_dir is set */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description A file could not be read */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_active_config_name: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ActiveConfigFile"]
        }
      }
    }
  }
  get_config: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The config, null if CamillaDSP has none */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Configuration"] | null
        }
      }
      /** @description CamillaDSP cannot be reached, or sent a config the GUI cannot read */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_config_file: {
    parameters: {
      query: {
        /** @description The file name, in config_dir. */
        name: string
        /** @description Bring a config for an older CamillaDSP up to date. */
        migrate?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Configuration"]
        }
      }
      /** @description The file is not a config the GUI can use, or could not be migrated */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description There is no such file */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_default_config_file: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Configuration"]
        }
      }
      /** @description No default config is set, or the file is missing */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description The file is not a config the GUI can use */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_config_at_gui_start: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StartConfig"]
        }
      }
      /** @description There is no config to start with */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description No config file could be read */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_gui_config: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["GuiConfig"]
        }
      }
    }
  }
  get_levels: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A `levels` event for each update from CamillaDSP */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "text/event-stream": components["schemas"]["VuLevels"]
        }
      }
      /** @description CamillaDSP cannot be reached, or the level stream is disabled in the settings */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_log_file: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "text/plain": string
        }
      }
      /** @description No log file is set, or it cannot be read */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_faders: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Fader"][]
        }
      }
      /** @description CamillaDSP cannot be reached, or refused */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  set_fader_mute: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The fader, 0 for the main volume */
        index: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "text/plain": boolean
      }
    }
    responses: {
      /** @description Set */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description CamillaDSP cannot be reached, or refused */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  set_fader_volume: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The fader, 0 for the main volume */
        index: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "text/plain": number
      }
    }
    responses: {
      /** @description Set */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description CamillaDSP cannot be reached, or refused */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_mute: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "text/plain": boolean
        }
      }
      /** @description CamillaDSP cannot be reached, or refused */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  set_mute: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "text/plain": boolean
      }
    }
    responses: {
      /** @description Set */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description CamillaDSP cannot be reached, or refused */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_volume: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "text/plain": number
        }
      }
      /** @description CamillaDSP cannot be reached, or refused */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  set_volume: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "text/plain": number
      }
    }
    responses: {
      /** @description Set */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description CamillaDSP cannot be reached, or refused */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  save_config_file: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveConfigBody"]
      }
    }
    responses: {
      /** @description Saved */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The file name is not valid */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description The config has paths outside the configured folders */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description The file could not be written */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  set_active_config_name: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActiveConfigBody"]
      }
    }
    responses: {
      /** @description Set */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The file name is not valid */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description CamillaDSP refused */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  set_config: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigBody"]
      }
    }
    responses: {
      /** @description Applied */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The config has paths outside the configured folders */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description The body is not a config, or CamillaDSP refused it */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description CamillaDSP cannot be reached */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_spectrum: {
    parameters: {
      query: {
        /** @description Which side to analyze: `"capture"` or `"playback"`. */
        side: "playback" | "capture"
        /** @description Channel to analyze. `null` averages all channels; an integer selects a single channel (zero-based). */
        channel?: number | null
        /** @description Lower edge of the frequency range in Hz. Must be > 0. */
        min_freq: number
        /** @description Upper edge of the frequency range in Hz. Must be > `min_freq`. */
        max_freq: number
        /** @description Number of output bins. Must be ≥ 2. */
        n_bins: number
        /** @description Maximum push rate in Hz. `None` = natural rate (one push per 50 % overlap hop). */
        max_rate?: number | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A `spectrum` event for each update from CamillaDSP */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "text/event-stream": components["schemas"]["SpectrumData"]
        }
      }
      /** @description Processing is not running (with the result `ProcessingNotRunningError`), CamillaDSP cannot be reached, or the level stream is disabled in the settings */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_state: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A `state` event with the current state, then one for each change */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "text/event-stream": components["schemas"]["StateUpdate"]
        }
      }
      /** @description CamillaDSP cannot be reached */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_status: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Status"]
        }
      }
    }
  }
  stop_processing: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Stopped */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description CamillaDSP refused */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description CamillaDSP cannot be reached */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  validate_config: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["Configuration"]
      }
    }
    responses: {
      /** @description Every issue, none if the config is valid */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ValidationIssue"][]
        }
      }
      /** @description The body is not JSON */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  get_wav_info: {
    parameters: {
      query: {
        /** @description A file name in audiofiles_dir, or a path. */
        filename: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WavInfo"]
        }
      }
      /** @description The file is outside audiofiles_dir */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
      /** @description The file is not a wav file CamillaDSP can read */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
  yaml_to_json: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportText"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ConfigFragment"]
        }
      }
      /** @description The text is not YAML, or not part of a config */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorBody"]
        }
      }
    }
  }
}
