---
hide_capture_samplerate: false
hide_silence: false
hide_capture_device: false
hide_playback_device: false
hide_rate_monitoring: false
hide_multithreading: false
apply_config_automatically: false
status_update_interval: 100
volume_range: 50
volume_max: 0
custom_shortcuts:
  - section: "Equalizer"
    description: |
      To use the EQ, add filters named "Bass" and "Treble" to the pipeline.

      Recommended settings:
      Bass: Biquad Lowshelf freq=85 q=0.9
      Treble: Biquad Highshelf freq=6500 q=0.7
    shortcuts:
      - name: "Treble (dB)"
        config_elements:
          - path: ["filters", "Treble", "parameters", "gain"]
        range_from: -12
        range_to: 12
        step: 0.5
      - name: "Bass (dB)"
        config_elements:
          - path: ["filters", "Bass", "parameters", "gain"]
        range_from: -12
        range_to: 12
        step: 0.5
#  - section: "Custom"
#    description: |
#      Demo for a few custom shortcuts.
#      For crossover example, add one biquad lowpass filter named "Lowpass",
#      and one highpass named "Highpass".
#
#      For the crossfade and switch examples,
#      add two gain filters named "GainA" and "GainB".
#    shortcuts:
#      - name: "Crossover freq"
#        config_elements:
#          - path: ["filters", "Lowpass", "parameters", "freq"]
#            reverse: false
#          - path: ["filters", "Highpass", "parameters", "freq"]
#            reverse: false
#        range_from: 1000
#        range_to: 1500
#        step: 10
#      - name: "Crossfade"
#        config_elements:
#          - path: ["filters", "GainA", "parameters", "gain"]
#            reverse: false
#          - path: ["filters", "GainB", "parameters", "gain"]
#            reverse: true
#        range_from: -20
#        range_to: 0
#        step: 0.5
#        type: "number"
#      - name: "Switch"
#        config_elements:
#          - path: ["filters", "GainA", "parameters", "mute"]
#            reverse: false
#          - path: ["filters", "GainB", "parameters", "mute"]
#            reverse: true
#        type: "boolean"