name: npm build

on: [push]

jobs:

  read_fe_tag:
    runs-on: ubuntu-latest
    outputs:
      fe_tag: ${{ steps.fe_tag_step.outputs.fe_tag }}
    steps:
    - uses: actions/checkout@v3
    - name: Get CamillaGUI tag from versions.yml
      id: fe_tag_step
      run: |
        FE_TAG=$(sed -n 's/camillagui_tag: \(.*\)$/\1/p' release_automation/versions.yml)
        echo "fe_tag=$FE_TAG" >> "$GITHUB_OUTPUT"

  build_fe:
    runs-on: ubuntu-latest
    needs: read_fe_tag
    steps:
    - uses: actions/checkout@v3
      env:
        FE_TAG: ${{ needs.read_fe_tag.outputs.fe_tag }}
      with:
        repository: HEnquist/camillagui
        ref: $FE_TAG
    - name: Build and publish
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build

  build_be:
    runs-on: ubuntu-latest
    needs: build_fe
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Run python tests
      run: python3 -m unittest discover -p "*_test.py"
    - name: Download frontend
      uses: actions/download-artifact@v3
    - name: Upload all
      uses: actions/upload-artifact@v3
      with:
        name: camillagui-backend
        path: |
          .
          !.git*