name: Publish

on:
  push:
    tags:
      - '*'

jobs:

  read_fe_tag:
    runs-on: ubuntu-latest
    outputs:
      fe_tag: ${{ steps.fe_tag_step.outputs.fe_tag }}
    steps:
    - uses: actions/checkout@v3
    - name: Get CamillaGUI tag from versions.yml
      id: fe_tag_step
      run: |
        FE_TAG=$(sed -n 's/camillagui_tag: \(.*\)$/\1/p' release_automation/versions.yml)
        echo "fe_tag=$FE_TAG" >> "$GITHUB_OUTPUT"

  build_fe:
    runs-on: ubuntu-latest
    needs: read_fe_tag
    steps:
    - uses: actions/checkout@v3
      with:
        repository: HEnquist/camillagui
        ref: ${{ needs.read_fe_tag.outputs.fe_tag }}
    - name: Build and publish
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build

  build_be:
    runs-on: ubuntu-latest
    needs: build_fe
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2 PyYAML
    
    - name: Render scripts from templates
      run: python release_automation/render_env_files.py

    - name: Download frontend
      uses: actions/download-artifact@v3
    - run: zip -r camillagui.zip *
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: camillagui.zip
        asset_name: camillagui.zip
        tag: ${{ github.ref }}