name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build_fe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: HEnquist/camillagui
        ref: v2.0.0-alpha2
    - name: Build and publish
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build

  build_be:
    runs-on: ubuntu-latest
    needs: build_fe
    steps:
    - uses: actions/checkout@v3
    - name: Download frontend
      uses: actions/download-artifact@v3
    - run: zip -r camillagui.zip *
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: camillagui.zip
        asset_name: camillagui.zip
        tag: ${{ github.ref }}